name: Install Terraform
description: Installs Terraform for other actions to use

runs:
  using: "composite"
  steps:
    - name: Add Terraform GPG Key
      shell: bash
      run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    - name: Add Terraform APT Repo
      shell: bash
      run: sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - name: Add Terraform Package
      shell: bash
      run: sudo apt-get update && sudo apt-get -y install terraform
